// Online play texts (CHE-271): English is the fallback passed to t(), German registered here (the i18n.js way for modules, addDE).
import { addDE } from '../i18n.js';

addDE({
  'online.tab': 'Online',
  'online.conn.connected': 'Server verbunden', 'online.conn.connecting': 'verbinde...', 'online.conn.unreachable': 'Server nicht erreichbar',
  'online.serverUpdating': 'Der Server wird gerade aktualisiert. Deine Partien sind sicher, bitte später nochmal schauen.',
  'online.details': 'Details', 'online.detailsTitle': 'Verbindung',
  'online.cause.offline': 'Dieses Gerät hat gerade kein Internet.', 'online.cause.noanswer': 'Der Server antwortet nicht.',
  'online.cause.server': 'Der Server hat einen Fehler.', 'online.cause.invite': 'Die Einladung gilt nicht mehr.',
  'online.lastOk': 'Zuletzt verbunden: {time}', 'online.neverOk': 'Noch nicht verbunden',
  'online.retryIn': 'Nächster Versuch in {s} s', 'online.retrying': 'Versuche gerade...',
  'online.retry': 'Nochmal versuchen', 'online.copy': 'Details kopieren', 'online.copied': 'Kopiert',
  'online.lockLine': 'Keine Verbindung, Zug geht gleich wieder',
  'online.needInvite': 'Online spielen geht nur mit Einladung. Bitte frag nach einem Einladungslink.',
  'online.codeLabel': 'Einladungscode eingeben', 'online.codeGo': 'Anmelden',
  'online.codeWrong': 'Dieser Code passt nicht.', 'online.codeSlow': 'Zu viele Versuche. Bitte warte ein paar Minuten.', 'online.codeNet': 'Keine Verbindung zum Server.',
  'online.you': 'Du bist {name}', 'online.players': 'Spieler', 'online.noPlayers': 'Noch niemand sonst ist eingeladen.',
  'online.botTag': 'Bot', 'online.botChallenge': 'Bot fordert mich heraus',
  'online.challenge': 'Herausfordern', 'online.playing': 'spielt', 'online.online': 'online', 'online.offline': 'nicht da',
  'online.challengesYou': '{name} fordert dich heraus', 'online.accept': 'Annehmen', 'online.decline': 'Nein danke',
  'online.waiting': 'Warte auf {name}...', 'online.declined': '{name} hat abgelehnt', 'online.ok': 'OK',
  'online.gameWith': 'Partie gegen {name}', 'online.youPlay': 'Du spielst {side}', 'online.yourTurn': 'Du bist am Zug', 'online.theirTurn': '{name} ist am Zug',
  'online.askedLine': 'Herausgefordert, wartet...', 'online.withdraw': 'Zurückziehen', 'online.incoming': 'fordert dich heraus', 'online.theirTurnCard': '{name} ist dran', 'online.yourTurnCard': 'Du bist dran', 'online.toGame': 'Zur Partie', 'online.onBoard': 'auf dem Brett',
  'online.running': 'Laufende Partien', 'online.moveNo': 'Zug {n}', 'online.since': 'seit {t}',
  'online.t.min': '{n} Min', 'online.t.h': '{n} Std', 'online.t.day': '{n} Tag', 'online.t.days': '{n} Tage',
  'online.limitYou': 'noch {t}, dann kannst du beenden', 'online.limitThem': 'noch {t}, dann gewinnt {name}',
  'online.limitYouNow': 'Du kannst die Partie jetzt beenden', 'online.limitThemNow': '{name} kann die Partie jetzt beenden',
  'online.hdrYou': 'Du bist dran ({side})', 'online.acceptedNote': '{name} hat angenommen', 'online.acceptedBubble': '♟ {name} hat angenommen · Zur Partie ›',
  'online.askPuzzle': 'Rätsel abbrechen und zur Partie?', 'online.askDrill': 'Übung abbrechen und zur Partie?', 'online.askExplain': 'Lektion abbrechen und zur Partie?', 'online.no': 'Nein',
  'online.sending': 'Zug wird gesendet...',
  'online.toBoard': 'Zur Partie', 'online.resign': 'Aufgeben', 'online.resignAsk': 'Partie wirklich aufgeben?', 'online.yes': 'Ja', 'online.cancel': 'Abbrechen',
  'online.finish': 'Partie beenden', 'online.finishHint': '{name} hat seit 3 Tagen nicht gezogen. Beenden zählt als Sieg für dich.',
  'online.won': 'Du hast gewonnen', 'online.lost': 'Du hast verloren', 'online.drawn': 'Remis',
  'online.scoreNow': 'Gegen {name} jetzt {score}', 'online.started': 'Partie gegen {name}. Du spielst {side}.',
  'online.chat': 'Chat', 'online.chatWith': 'Chat mit {name}', 'online.message': 'Nachricht', 'online.send': 'Senden',
  'online.monitored': 'Chat wird mitgelesen', 'online.muted': 'Du kannst gerade nicht schreiben.', 'online.noMessages': 'Noch keine Nachrichten.',
  'online.chatFailed': 'Nachricht nicht gesendet.', 'online.bubbleMsg': '💬 {name}: {text} ›', 'online.bubbleOne': '💬 {name}: {text}{more} ›',
  'online.bubbleMany': '💬 {n} neue Nachrichten von {names} ›', 'online.and': 'und', 'online.gameLine': 'Online gegen {name} · {turn}', 'online.gameBubble': '♟ Partie gegen {name}: {turn} ›', 'online.movedBubble': '♟ {name} hat gezogen: {turn} ›', 'online.bubbleHide': 'Ausblenden', 'online.close': 'Schließen',
  'online.monitoredShort': 'mitgelesen', 'online.minimize': 'Verkleinern', 'online.noGameYet': 'noch keine Partie', 'online.waitingShort': 'Warte auf {name}', 'online.asked': 'Gefragt', 'online.you2': 'Du',
  'online.pushAsk': 'Soll ich dir Bescheid sagen, wenn du dran bist?', 'online.pushYes': 'Ja, gern', 'online.pushNo': 'Nein danke',
  'online.bellOn': 'Benachrichtigungen an', 'online.bellOff': 'Benachrichtigungen aus', 'online.bellDenied': 'Benachrichtigungen sind im Browser gesperrt',
  'online.bellInstall': 'Zum Home-Bildschirm hinzufügen, dann gibt es Benachrichtigungen', 'online.pushFailed': 'Das hat nicht geklappt.', 'online.pushServerOff': 'Der Server schickt gerade keine Benachrichtigungen.',
  'online.yourCode': 'Dein Code', 'online.yourCodeHint': 'Tippe ihn in der App vom Home-Bildschirm ein, dann bist du dort angemeldet.',
  'online.st.title': 'Zahlen von {name}', 'online.st.own': 'Deine Zahlen', 'online.st.games': 'Partien', 'online.st.wins': 'Siege', 'online.st.losses': 'Niederlagen', 'online.st.draws': 'Remis', 'online.st.streak': 'Serie',
  'online.st.none': 'noch keine Partie', 'online.st.loading': 'Lade Zahlen...', 'online.st.failed': 'Die Zahlen sind gerade nicht da.', 'online.st.open': 'Zahlen von {name}',
  'online.st.h2h': 'Gegeneinander', 'online.st.h2hLine': 'Du {score} {name}', 'online.st.h2hNone': 'Noch nie gegeneinander gespielt',
  'online.st.s.win1': '1 Sieg', 'online.st.s.winN': '{n} Siege in Folge', 'online.st.s.loss1': '1 Niederlage', 'online.st.s.lossN': '{n} Niederlagen in Folge', 'online.st.s.draw1': '1 Remis', 'online.st.s.drawN': '{n} Remis in Folge',
  'online.st.nowStreak': 'Jetzt', 'online.st.bestStreak': 'Beste Siegesserie', 'online.st.bestN': '{n} Siege',
  'online.st.avgLen': 'Länge im Schnitt', 'online.st.lenN': '{n} Züge', 'online.st.avgTime': 'Dauer im Schnitt', 'online.st.timeN': '{n} Min.', 'online.st.openings': 'Lieblingseröffnungen',
  'banner.resign': 'Aufgegeben', 'banner.stale': 'Partie beendet',
  'reason.resign': 'Aufgegeben', 'reason.stale': '3 Tage kein Zug',
});
