// Naming a position. The map (catalogue-data.js, generated by tools/build-catalogue.mjs) is about 450 KB, so it is a
// separate chunk fetched on first use. A name is found by position key (Chess#positionKey4), however the position
// was reached. An unknown position is normal: most positions are not named openings.
let map = null, loading = null;

export function loadCatalogue() {
  if (map) return Promise.resolve(map);
  loading ||= import('./catalogue-data.js').then((m) => (map = m.MAP));
  return loading;
}

export const catalogueLoaded = () => map !== null;

// { eco, name } for a position key, or null. Needs loadCatalogue() to have resolved, else null.
export function nameOf(key) {
  const e = map && map[key];
  return e ? { eco: e[0], name: e[1] } : null;
}

// The deepest named position along a line (keys in order). A line can run past its last named position, so the
// question "what is this line called" is answered by walking it and keeping the last name found.
export function nameOfLine(keys) {
  let deepest = null;
  for (const k of keys) deepest = nameOf(k) || deepest;
  return deepest;
}
